### ISSUE TITLE
Update read me file.

### ISSUE THREAD

**Issue by Devemmy01** [ndm13/youtube-fm#12]
looking at line 3 in the overview section, it should be " It's recommended that users should not " instead of " It's recommended that users not  " 
can I make a change to that?

**Comment by ndm13** [comment]
I feel that it's grammatically correct. [Dropping "should" from "be" or "have"](https://ell.stackexchange.com/q/1396) has different semantics, although the meaning is the same in this case.

I can add the `should` for clarity.
